spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db3
    password: root123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

